In [60]:
import os

import numpy as np
import pandas as pd


DATA_PATH = '../../data/'

In [64]:

def load_pbp_season(year):
    return pd.read_csv(os.path.join(DATA_PATH, f'ESPN/pbp/{year}.csv'))


pbp = load_pbp_season(2018)

In [88]:


pbp

,shooting_play,sequence_number,period_display_value,period_number,home_score,coordinate_x,coordinate_y,scoring_play,clock_display_value,team_id,...,lag_game_half,lead_game_half,start_quarter_seconds_remaining,start_half_seconds_remaining,start_game_seconds_remaining,game_play_number,end_quarter_seconds_remaining,end_half_seconds_remaining,end_game_seconds_remaining,period
0,False,101799901,1st Half,1,0,25.0,0.0,False,20:00,153.0,...,NaN,1.0,1200,1800,3000,1,600.0,1200.0,2400.0,1
1,False,101805301,1st Half,1,0,25.0,0.0,False,19:46,153.0,...,1.0,1.0,1186,1786,2986,2,1200.0,1800.0,3000.0,1
2,False,101805302,1st Half,1,0,25.0,0.0,False,19:46,153.0,...,1.0,1.0,1186,1786,2986,3,1186.0,1786.0,2986.0,1
3,True,101807101,1st Half,1,0,11.0,19.0,True,19:28,2460.0,...,1.0,1.0,1168,1768,2968,4,1186.0,1786.0,2986.0,1
4,True,101808701,1st Half,1,0,43.0,15.0,False,19:12,153.0,...,1.0,1.0,1152,1752,2952,5,1168.0,1768.0,2968.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1793523,False,102998601,2nd Half,2,67,25.0,0.0,False,0:13,2640.0,...,1.0,1.0,13,13,1213,334,14.0,14.0,1214.0,2
1793524,False,102998602,2nd Half,2,67,25.0,0.0,False,0:13,2029.0,...,1.0,1.0,13,13,1213,335,13.0,13.0,1213.0,2
1793525,True,102998801,2nd Half,2,69,27.0,2.0,True,0:11,2029.0,...,1.0,1.0,11,11,1211,336,13.0,13.0,1213.0,2
1793526,False,102999801,2nd Half,2,69,25.0,0.0,False,0:01,2640.0,...,1.0,1.0,1,1,1201,337,11.0,11.0,1211.0,2
1793527,False,102999901,2nd Half,2,69,50.0,-5.0,False,0:00,NaN,...,1.0,NaN,0,0,1200,338,1.0,1.0,1201.0,2

In [83]:



pbp.loc[pbp['type_text']=='Not Available']['text'].value_counts().head(20)

Official TV Timeout                           1076
 Official TV Timeout                           613
Bryce Brown missed Three Point Jumper.          25
Marcquise Reed missed Three Point Jumper.       23
Grayson Allen missed Three Point Jumper.        18
Reed Timmer missed Three Point Jumper.          17
Matt Frierson missed Three Point Jumper.        17
Ryan Taylor missed Jumper.                      17
Tony Carr missed Jumper.                        16
Max Strus missed Three Point Jumper.            16
Jordan Fox missed Three Point Jumper.           16
Jahmal McMurray missed Three Point Jumper.      16
Marvin Smith missed Three Point Jumper.         15
Shawn Williams missed Three Point Jumper.       15
Jordan Horn missed Three Point Jumper.          15
Gabe DeVoe missed Three Point Jumper.           15
Tyler Cook missed Jumper.                       15
Josh Okogie missed Three Point Jumper.          14
Trent Frazier missed Three Point Jumper.        14
Keita Bates-Diop missed Jumper.                 14
Name: text, dtype: int64

In [78]:
pbp['type_text'].value_counts()

Defensive Rebound        278476
Three Point Jump Shot    226588
MadeFreeThrow            214681
PersonalFoul             187549
LayUpShot                184093
JumpShot                 166550
Lost Ball Turnover       135700
Offensive Rebound        112136
Steal                     68531
Not Available             41861
OfficialTVTimeOut         40492
Block Shot                37155
Dead Ball Rebound         30297
ShortTimeOut              21937
DunkShot                  20180
TipShot                    6891
End Period                 6210
End Game                   5270
RegularTimeOut             4489
Jumpball                   2622
Technical Foul             1820
Name: type_text, dtype: int64

In [70]:

import seaborn as sns



list(pbp)

['shooting_play',
 'sequence_number',
 'period_display_value',
 'period_number',
 'home_score',
 'coordinate_x',
 'coordinate_y',
 'scoring_play',
 'clock_display_value',
 'team_id',
 'type_id',
 'type_text',
 'away_score',
 'id',
 'text',
 'score_value',
 'participants_0_athlete_id',
 'participants_1_athlete_id',
 'media_id',
 'season',
 'season_type',
 'away_team_id',
 'away_team_name',
 'away_team_mascot',
 'away_team_abbrev',
 'away_team_name_alt',
 'home_team_id',
 'home_team_name',
 'home_team_mascot',
 'home_team_abbrev',
 'home_team_name_alt',
 'home_team_spread',
 'game_spread',
 'home_favorite',
 'game_spread_available',
 'game_id',
 'qtr',
 'time',
 'clock_minutes',
 'clock_seconds',
 'half',
 'game_half',
 'lag_qtr',
 'lead_qtr',
 'lag_game_half',
 'lead_game_half',
 'start_quarter_seconds_remaining',
 'start_half_seconds_remaining',
 'start_game_seconds_remaining',
 'game_play_number',
 'end_quarter_seconds_remaining',
 'end_half_seconds_remaining',
 'end_game_seconds_remaining',
 'period']

In [42]:

import ast
def clean_notes(x):
    
    """
    Not much useful info here, might just one hot encode
    """
    print(x)
#     x = x.replace('"', '')
    x = x.replace("AARON'S", 'AARONS')
    print(x)
    x = ast.literal_eval(x)
    if ((type(x)==list)&(len(x) > 0)):
        note_data = x[0]
        x = note_data['headline']
        
    return x

# schedule['notes'] = schedule['notes'].apply(lambda x: clean_notes(x))

In [47]:


def main_clean(df):
    
    df.columns=[col.replace('.','_') for col in list(df)]
        
    df['start_date'] = pd.to_datetime(df['start_date'].copy())
    
    
    
    return df

/var/folders/6j/0sqk1ykn5f10xfsflg6djktr0000gn/T/ipykernel_69905/2250709946.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  schedule.sum()

id                                                             2318134356398
uid                        s:40~l:41~e:401022817~c:401022817s:40~l:41~e:4...
date                       2018-03-29T23:00Z2018-03-28T01:34Z2018-03-27T2...
attendance                                                          26216428
timeValid                                                               5781
neutralSite                                                              613
conferenceCompetition                                                   3238
recent                                                                     0
notes                      [{'type': 'event', 'headline': 'NIT - CHAMPION...
startDate                  2018-03-29T23:00Z2018-03-28T01:34Z2018-03-27T2...
type.id                                                               2175.0
venue.id                                                            12057155
venue.fullName             Madison Square GardenMadison Square GardenMadi...
venue.address.city         New YorkNew YorkNew YorkMoragaStillwaterLouisv...
venue.address.state        NYNYNYCAOKKYWICACAUTOKKYWITXINWACAUTMSPAWILACA...
venue.capacity                                                      47074703
venue.indoor                                                            5735
status.clock                                                             348
status.displayClock        0:000:000:000:000:000:000:000:000:000:000:000:...
status.period                                                          12007
status.type.id                                                         17401
status.type.name           STATUS_FINALSTATUS_FINALSTATUS_FINALSTATUS_FIN...
status.type.state          postpostpostpostpostpostpostpostpostpostpostpo...
status.type.completed                                                   5763
status.type.description    FinalFinalFinalFinalFinalFinalFinalFinalFinalF...
status.type.detail         FinalFinalFinalFinal/OTFinalFinalFinalFinalFin...
status.type.shortDetail    FinalFinalFinalFinal/OTFinalFinalFinalFinalFin...
home.id                                                              9461528
home.uid                   s:40~l:41~t:254s:40~l:41~t:213s:40~l:41~t:254s...
home.location              UtahPenn StateUtahSaint Mary'sOklahoma StateLo...
home.name                  UtesNittany LionsUtesGaelsCowboysCardinalsGold...
home.abbreviation          UTAHPSUUTAHSMCOKSTLOUMARQUSCSMCUTAHOKSTLOUMARQ...
home.displayName           Utah UtesPenn State Nittany LionsUtah UtesSain...
home.shortDisplayName      UtahPenn StateUtahSaint Mary'sOklahoma StateLo...
home.color                 89001200265D890012003768FF6500ad000a083963ffc7...
home.isActive                                                           5774
home.venue.id                                                     12109213.0
home.conferenceId                                                   112454.0
away.id                                                             15704824
away.uid                   s:40~l:41~t:213s:40~l:41~t:344s:40~l:41~t:98s:...
away.location              Penn StateMississippi StateWestern KentuckyUta...
away.abbreviation          PSUMSSTWKUUTAHWKUMSSTPSUWKUWASHLSUSTANMTSUOREM...
away.displayName           Penn State Nittany LionsMississippi State Bull...
away.shortDisplayName      Penn StateMississippi StWestern KYUtahWestern ...
away.isActive                                                           5324
away.venue.id                                                     11415014.0
away.conferenceId                                                   105151.0
game_id                                                        2318134356398
season_type                                                            11593
season                                                              11666058
groups.id                                                            62982.0
groups.isConference                                                     3238
tournamentId                                                          6019.0
PBP                                                                     5415
team_box                                                                5762
player_box                                                              5762
dtype: object

In [43]:

list(schedule)

['id',
 'uid',
 'date',
 'attendance',
 'timeValid',
 'neutralSite',
 'conferenceCompetition',
 'recent',
 'notes',
 'startDate',
 'type.id',
 'type.abbreviation',
 'venue.id',
 'venue.fullName',
 'venue.address.city',
 'venue.address.state',
 'venue.capacity',
 'venue.indoor',
 'status.clock',
 'status.displayClock',
 'status.period',
 'status.type.id',
 'status.type.name',
 'status.type.state',
 'status.type.completed',
 'status.type.description',
 'status.type.detail',
 'status.type.shortDetail',
 'home.id',
 'home.uid',
 'home.location',
 'home.name',
 'home.abbreviation',
 'home.displayName',
 'home.shortDisplayName',
 'home.color',
 'home.alternateColor',
 'home.isActive',
 'home.venue.id',
 'home.logo',
 'home.conferenceId',
 'away.id',
 'away.uid',
 'away.location',
 'away.name',
 'away.abbreviation',
 'away.displayName',
 'away.shortDisplayName',
 'away.color',
 'away.alternateColor',
 'away.isActive',
 'away.venue.id',
 'away.logo',
 'away.conferenceId',
 'game_id',
 'season_type',
 'status.type.altDetail',
 'season',
 'groups.id',
 'groups.name',
 'groups.shortName',
 'groups.isConference',
 'tournamentId',
 'PBP',
 'team_box',
 'player_box']

0    401022817
1    401022816
2    401022815
3    401022814
4    401022813
Name: id, dtype: int64
0    s:40~l:41~e:401022817~c:401022817
1    s:40~l:41~e:401022816~c:401022816
2    s:40~l:41~e:401022815~c:401022815
3    s:40~l:41~e:401022814~c:401022814
4    s:40~l:41~e:401022813~c:401022813
Name: uid, dtype: object
0    2018-03-29T23:00Z
1    2018-03-28T01:34Z
2    2018-03-27T23:00Z
3    2018-03-22T02:00Z
4    2018-03-22T00:00Z
Name: date, dtype: object
0    11175
1     7865
2        0
3     2309
4    11308
Name: attendance, dtype: int64
0    True
1    True
2    True
3    True
4    True
Name: timeValid, dtype: bool
0     True
1     True
2     True
3    False
4    False
Name: neutralSite, dtype: bool
0    False
1    False
2    False
3    False
4    False
Name: conferenceCompetition, dtype: bool
0    False
1    False
2    False
3    False
4    False
Name: recent, dtype: bool
0    [{'type': 'event', 'headline': 'NIT - CHAMPION...
1    [{'type': 'event', 'headline': 'NIT - SEMIFINA...
2    [{'type': 'event', 'headline': 'NIT - SEMIFINA...
3    [{'type': 'event', 'headline': 'NIT - QUARTERF...
4    [{'type': 'event', 'headline': 'NIT - QUARTERF...
Name: notes, dtype: object
0    2018-03-29T23:00Z
1    2018-03-28T01:34Z
2    2018-03-27T23:00Z
3    2018-03-22T02:00Z
4    2018-03-22T00:00Z
Name: startDate, dtype: object
0    NaN
1    1.0
2    NaN
3    NaN
4    NaN
Name: type.id, dtype: float64
0    NaN
1    STD
2    NaN
3    NaN
4    NaN
Name: type.abbreviation, dtype: object
0    1830
1    1830
2    1830
3     488
4    1992
Name: venue.id, dtype: int64
0               Madison Square Garden
1               Madison Square Garden
2               Madison Square Garden
3    University Credit Union Pavilion
4                 Gallagher-Iba Arena
Name: venue.fullName, dtype: object
0      New York
1      New York
2      New York
3        Moraga
4    Stillwater
Name: venue.address.city, dtype: object
0    NY
1    NY
2    NY
3    CA
4    OK
Name: venue.address.state, dtype: object
0    19812
1    19812
2    19812
3     3500
4    13611
Name: venue.capacity, dtype: int64
0    True
1    True
2    True
3    True
4    True
Name: venue.indoor, dtype: bool
0    0
1    0
2    0
3    0
4    0
Name: status.clock, dtype: int64
0    0:00
1    0:00
2    0:00
3    0:00
4    0:00
Name: status.displayClock, dtype: object
0    4
1    4
2    4
3    5
4    4
Name: status.period, dtype: int64
0    3
1    3
2    3
3    3
4    3
Name: status.type.id, dtype: int64
0    STATUS_FINAL
1    STATUS_FINAL
2    STATUS_FINAL
3    STATUS_FINAL
4    STATUS_FINAL
Name: status.type.name, dtype: object
0    post
1    post
2    post
3    post
4    post
Name: status.type.state, dtype: object
0    True
1    True
2    True
3    True
4    True
Name: status.type.completed, dtype: bool
0    Final
1    Final
2    Final
3    Final
4    Final
Name: status.type.description, dtype: object
0       Final
1       Final
2       Final
3    Final/OT
4       Final
Name: status.type.detail, dtype: object
0       Final
1       Final
2       Final
3    Final/OT
4       Final
Name: status.type.shortDetail, dtype: object
0     254
1     213
2     254
3    2608
4     197
Name: home.id, dtype: int64
0     s:40~l:41~t:254
1     s:40~l:41~t:213
2     s:40~l:41~t:254
3    s:40~l:41~t:2608
4     s:40~l:41~t:197
Name: home.uid, dtype: object
0              Utah
1        Penn State
2              Utah
3      Saint Mary's
4    Oklahoma State
Name: home.location, dtype: object
0             Utes
1    Nittany Lions
2             Utes
3            Gaels
4          Cowboys
Name: home.name, dtype: object
0    UTAH
1     PSU
2    UTAH
3     SMC
4    OKST
Name: home.abbreviation, dtype: object
0                   Utah Utes
1    Penn State Nittany Lions
2                   Utah Utes
3          Saint Mary's Gaels
4      Oklahoma State Cowboys
Name: home.displayName, dtype: object
0              Utah
1        Penn State
2              Utah
3      Saint Mary's
4    Oklahoma State
Name: home.shortDisplayName, dtype: object
0    890012
1    00265D
2    890012
3    003768
4    FF6500
Name: home.color, dtype: object
0    7e8083
1    002e5c
2    7e8083
3    d02f35
4    ff9900
Name: home.alternateColor, dtype: object
0    True
1    True
2    True
3    True
4    True
Name: home.isActive, dtype: bool
0    2196.0
1    1942.0
2    2196.0
3     488.0
4    1992.0
Name: home.venue.id, dtype: float64
0    https://a.espncdn.com/i/teamlogos/ncaa/500/254...
1    https://a.espncdn.com/i/teamlogos/ncaa/500/213...
2    https://a.espncdn.com/i/teamlogos/ncaa/500/254...
3    https://a.espncdn.com/i/teamlogos/ncaa/500/260...
4    https://a.espncdn.com/i/teamlogos/ncaa/500/197...
Name: home.logo, dtype: object
0    21.0
1     7.0
2    21.0
3    29.0
4     8.0
Name: home.conferenceId, dtype: float64
0    213
1    344
2     98
3    254
4     98
Name: away.id, dtype: int64
0    s:40~l:41~t:213
1    s:40~l:41~t:344
2     s:40~l:41~t:98
3    s:40~l:41~t:254
4     s:40~l:41~t:98
Name: away.uid, dtype: object
0           Penn State
1    Mississippi State
2     Western Kentucky
3                 Utah
4     Western Kentucky
Name: away.location, dtype: object
0    Nittany Lions
1         Bulldogs
2      Hilltoppers
3             Utes
4      Hilltoppers
Name: away.name, dtype: object
0     PSU
1    MSST
2     WKU
3    UTAH
4     WKU
Name: away.abbreviation, dtype: object
0        Penn State Nittany Lions
1      Mississippi State Bulldogs
2    Western Kentucky Hilltoppers
3                       Utah Utes
4    Western Kentucky Hilltoppers
Name: away.displayName, dtype: object
0        Penn State
1    Mississippi St
2        Western KY
3              Utah
4        Western KY
Name: away.shortDisplayName, dtype: object
0    00265D
1    762123
2    F32026
3    890012
4    F32026
Name: away.color, dtype: object
0    002e5c
1    c8c8c8
2    b3b5b8
3    7e8083
4    b3b5b8
Name: away.alternateColor, dtype: object
0    True
1    True
2    True
3    True
4    True
Name: away.isActive, dtype: bool
0    1942.0
1    2095.0
2    1971.0
3    2196.0
4    1971.0
Name: away.venue.id, dtype: float64
0    https://a.espncdn.com/i/teamlogos/ncaa/500/213...
1    https://a.espncdn.com/i/teamlogos/ncaa/500/344...
2    https://a.espncdn.com/i/teamlogos/ncaa/500/98.png
3    https://a.espncdn.com/i/teamlogos/ncaa/500/254...
4    https://a.espncdn.com/i/teamlogos/ncaa/500/98.png
Name: away.logo, dtype: object
0     7.0
1    23.0
2    11.0
3    21.0
4    11.0
Name: away.conferenceId, dtype: float64
0    401022817
1    401022816
2    401022815
3    401022814
4    401022813
Name: game_id, dtype: int64
0    3
1    3
2    3
3    3
4    3
Name: season_type, dtype: int64
0    NaN
1    NaN
2    NaN
3     OT
4    NaN
Name: status.type.altDetail, dtype: object
0    2018
1    2018
2    2018
3    2018
4    2018
Name: season, dtype: int64
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: groups.id, dtype: float64
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: groups.name, dtype: object
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: groups.shortName, dtype: object
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: groups.isConference, dtype: object
0    21.0
1    21.0
2    21.0
3    21.0
4    21.0
Name: tournamentId, dtype: float64
0    True
1    True
2    True
3    True
4    True
Name: PBP, dtype: bool
0    True
1    True
2    True
3    True
4    True
Name: team_box, dtype: bool
0    True
1    True
2    True
3    True
4    True
Name: player_box, dtype: bool